name: Frontend Tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    frontend-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "14"

            - name: Install dependencies
              run: |
                  cd /Web_Application/jokes-frontend
                  npm install

            - name: Run tests
              run: |
                  cd /Web_Application/jokes-frontend
                  npm test
